apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-frontend
  labels:
    name: pv-frontend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mi-clase"
  hostPath:
    path: /mnt/sitio-despliegue
