apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frontend
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "mi-clase"
  selector:
    matchLabels:
      name: pv-frontend
