apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-portal
  template:
    metadata:
      labels:
        app: frontend-portal
    spec:
      containers:
      - name: nginx-frontend
        image: nginx
        volumeMounts:
        - name: volume-portal
          mountPath: /usr/share/nginx/html
      volumes:
      - name: volume-portal
        persistentVolumeClaim:
          claimName: pvc-frontend
